vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO FreeCAD/FreeCAD
    REF "${VERSION}"
    SHA512 69a82c0af45137079b1ce184a4a3df475c005da66b4a4cab17371a1f62432b13f721e3da8b350b3ad50125c939cdfa5fed477e0605d52bd8fcee3c528931a185
    HEAD_REF main
    PATCHES
        # This function needed when compile gui component.
        # remove this patch when you add the gui feature
        remove_qt_add_translation_function.patch
)

vcpkg_add_to_path(PREPEND "${CURRENT_INSTALLED_DIR}/tools/Qt6/bin/")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_FORCE_DIRECTORY=OFF
        -DBUILD_GUI=OFF
        -DFREECAD_USE_EXTERNAL_ZIPIOS=OFF
        -DFREECAD_USE_EXTERNAL_SMESH=OFF
        -DFREECAD_USE_EXTERNAL_KDL=OFF
        -DFREECAD_USE_EXTERNAL_FMT=ON
        -DFREECAD_USE_EXTERNAL_ONDSELSOLVER=OFF
        -DFREECAD_USE_EXTERNAL_E57FORMAT=OFF
        -DFREECAD_USE_EXTERNAL_GTEST=OFF
        -DFREECAD_USE_FREETYPE=OFF
        -DFREECAD_BUILD_DEBIAN=OFF
        -DFREECAD_CHECK_PIVY=OFF
        -DFREECAD_PARALLEL_COMPILE_JOBS=OFF
        -DFREECAD_PARALLEL_LINK_JOBS=OFF
        -DBUILD_WITH_CONDA=OFF
        -DBUILD_DYNAMIC_LINK_PYTHON=OFF
        -DBUILD_TRACY_FRAME_PROFILER=OFF
        -DINSTALL_TO_SITEPACKAGES=OFF
        -DINSTALL_PREFER_SYMLINKS=OFF
        -DOCCT_CMAKE_FALLBACK=OFF
        -DFREECAD_USE_QT_FILEDIALOG=OFF
        -DFREECAD_RELEASE_PDB=OFF
        -DFREECAD_RELEASE_SEH=OFF
        -DFREECAD_LIBPACK_USE=OFF
        -DFREECAD_USE_PCH=OFF
        -DFREECAD_INSTALL_DEPEND_DIRS=OFF
        -DFREECAD_COPY_DEPEND_DIRS_TO_BUILD=OFF
        -DFREECAD_COPY_LIBPACK_BIN_TO_BUILD=OFF
        -DFREECAD_COPY_PLUGINS_BIN_TO_BUILD=OFF
        -DFREECAD_WARN_ERROR=OFF
        -DBUILD_DESIGNER_PLUGIN=OFF
        -DFREECAD_CREATE_MAC_APP=OFF
        -DBUILD_FEM=OFF
        -DBUILD_SANDBOX=OFF
        -DBUILD_TEMPLATE=OFF
        -DBUILD_ADDONMGR=OFF
        -DBUILD_BIM=OFF
        -DBUILD_DRAFT=OFF
        -DBUILD_DRAWING=OFF
        -DBUILD_HELP=OFF
        -DBUILD_IDF=OFF
        -DBUILD_IMPORT=OFF
        -DBUILD_INSPECTION=OFF
        -DBUILD_JTREADER=OFF
        -DBUILD_MATERIAL=OFF
        -DBUILD_MATERIAL_EXTERNAL=OFF
        -DBUILD_MESH=OFF
        -DBUILD_SMESH=OFF
        -DBUILD_MESH_PART=OFF
        -DBUILD_FLAT_MESH=OFF
        -DBUILD_OPENSCAD=OFF
        -DBUILD_PART=OFF
        -DBUILD_PART_DESIGN=OFF
        -DBUILD_CAM=OFF
        -DBUILD_ASSEMBLY=OFF
        -DBUILD_PLOT=OFF
        -DBUILD_POINTS=OFF
        -DBUILD_REVERSEENGINEERING=OFF
        -DBUILD_ROBOT=OFF
        -DBUILD_SHOW=OFF
        -DBUILD_SKETCHER=OFF
        -DBUILD_SPREADSHEET=OFF
        -DBUILD_START=OFF
        -DBUILD_TEST=OFF
        -DBUILD_MEASURE=OFF
        -DBUILD_TECHDRAW=OFF
        -DBUILD_TUX=OFF
        -DBUILD_WEB=OFF
        -DBUILD_SURFACE=OFF
        -DBUILD_VR=OFF
        -DBUILD_CLOUD=OFF
        -DENABLE_DEVELOPER_TESTS=OFF
        -DFREECAD_USE_3DCONNEXION_LEGACY=OFF
        -DBUILD_FEM_NETGEN=OFF
        -DFREECAD_USE_PCL=OFF
        -DUSE_CUDA=OFF
        -DUSE_OPENCV=OFF
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_fixup_pkgconfig()

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
